# Generated by Django 4.0.2 on 2022-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('account_active', models.BooleanField(default=True)),
                ('phoneno', models.CharField(blank=True, max_length=11)),
                ('image', models.ImageField(default='', upload_to='')),
                ('totacreditpoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
