# Generated by Django 4.0.2 on 2022-02-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_title', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('is_paid', models.BooleanField()),
                ('price', models.IntegerField()),
                ('num_subscribers', models.IntegerField()),
                ('num_reviews', models.IntegerField()),
                ('num_lectures', models.IntegerField()),
                ('level', models.CharField(max_length=20)),
                ('content_duration', models.FloatField()),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
