# Generated by Django 4.0.2 on 2022-02-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_store_courses'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store_courses',
            table='store_courses',
        ),
    ]
